<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>if</string>
	</array>
	<key>name</key>
	<string>Flounder</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(interface)\s+([A-z_]+[0-9]*)\s+(".*")\s+{</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.flounder</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.flounder</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double.flounder</string>
				</dict>
			</dict>
			<key>end</key>
			<string>}</string>
			<key>name</key>
			<string>meta.interface.flounder</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(rpc|message|call|response)\s+([A-z_0-9]+)\s*\(</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.flounder</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.flounder</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\)</string>
					<key>name</key>
					<string>meta.function.flounder</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>storage.modifier</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>support.type</string>
								</dict>
								<key>4</key>
								<dict>
									<key>name</key>
									<string>variable.parameter</string>
								</dict>
								<key>6</key>
								<dict>
									<key>name</key>
									<string>meta.array.length.flounder</string>
								</dict>
							</dict>
							<key>match</key>
							<string>\s*((in\s+|out\s+){0,1})\s*([A-z_]+[0-9]*)\s+([\w_0-9]+)(\[([A-z_0-9]+)\]){0,1}\s*,{0,1}*</string>
							<key>name</key>
							<string>meta.arguments.flounder</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#commentblock</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#commentline</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(typedef)\s+([A-z_0-9]+)\s+\{{0,1}</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.flounder</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.type</string>
						</dict>
					</dict>
					<key>end</key>
					<string>;</string>
					<key>name</key>
					<string>meta.typedef.flounder</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>support.type</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>meta.struct.name.flounder</string>
								</dict>
							</dict>
							<key>match</key>
							<string>([A-z_0-9]+)\s+([A-z_0-9]+);</string>
							<key>name</key>
							<string>meta.struct.entries.flounder</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#commentblock</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#commentline</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.flounder</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.type</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(alias)\s+([A-z_0-9]+)\s+([A-z_0-9]+)\s*;</string>
					<key>name</key>
					<string>meta.alias.flounder</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#commentblock</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#commentline</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#commentblock</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#commentline</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>commentblock</key>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.flounder</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<key>commentline</key>
		<dict>
			<key>match</key>
			<string>//.*</string>
			<key>name</key>
			<string>comment.line.flounder</string>
		</dict>
		<key>constant_binary</key>
		<dict>
			<key>match</key>
			<string>\b(0b[0-1]+)</string>
			<key>name</key>
			<string>constant.numeric.integer.binary.flounder</string>
		</dict>
		<key>constant_decimal</key>
		<dict>
			<key>match</key>
			<string>\b([1-9]+[0-9]*|0)</string>
			<key>name</key>
			<string>constant.numeric.integer.decimal.flounder</string>
		</dict>
		<key>constant_hex</key>
		<dict>
			<key>match</key>
			<string>\b(?i:(0x\h*))</string>
			<key>name</key>
			<string>constant.numeric.integer.hexadecimal.flounder</string>
		</dict>
		<key>string</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.flounder</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>flounder</string>
	<key>uuid</key>
	<string>945ed672-7a74-4ecf-8719-e13cc63ccdc3</string>
</dict>
</plist>
