<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>hl</string>
	</array>
	<key>name</key>
	<string>Hamlet</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.hamlet</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.type</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(define)\s+([A-z_0-9]+)\s+([A-z_0-9]+)\s*;</string>
			<key>name</key>
			<string>meta.alias.flounder</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(cap)\s+([A-z_0-9]+)\s+([A-z_0-9]+)\s*\{</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.hamlet</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.type</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string>meta.cap.hamlet</string>
			<key>patterns</key>
			<array>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#commentblock</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#commentline</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>commentblock</key>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.flounder</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<key>commentline</key>
		<dict>
			<key>match</key>
			<string>//.*</string>
			<key>name</key>
			<string>comment.line.flounder</string>
		</dict>
		<key>constant_binary</key>
		<dict>
			<key>match</key>
			<string>\b(0b[0-1]+)</string>
			<key>name</key>
			<string>constant.numeric.integer.binary.flounder</string>
		</dict>
		<key>constant_decimal</key>
		<dict>
			<key>match</key>
			<string>\b([1-9]+[0-9]*|0)</string>
			<key>name</key>
			<string>constant.numeric.integer.decimal.flounder</string>
		</dict>
		<key>constant_hex</key>
		<dict>
			<key>match</key>
			<string>\b(?i:(0x\h*))</string>
			<key>name</key>
			<string>constant.numeric.integer.hexadecimal.flounder</string>
		</dict>
		<key>string</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.flounder</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>hamlet</string>
	<key>uuid</key>
	<string>f76212bd-af6a-45a9-bc07-84987fbeb2a7</string>
</dict>
</plist>
