<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>dev</string>
	</array>
	<key>name</key>
	<string>Mackerel</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>device|regtype|register|constants|space|datatype|regarray</string>
			<key>name</key>
			<string>keyword.control.mackerel</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.mackerel</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.mackerel</string>
		</dict>
		<dict>
			<key>match</key>
			<string>//.*</string>
			<key>name</key>
			<string>comment.line.mackerel</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(0b[0-1]+)</string>
			<key>name</key>
			<string>constant.numeric.integer.binary.mackerel</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:(0x\h*))</string>
			<key>name</key>
			<string>constant.numeric.integer.hexadecimal.mackerel</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b([1-9]+[0-9]*|0)</string>
			<key>name</key>
			<string>constant.numeric.integer.decimal.mackerel</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.mackerel</string>
				</dict>
			</dict>
			<key>match</key>
			<string>type\(([A-z0-9_]+)\)</string>
			<key>name</key>
			<string>support.function.mackerel</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.mackerel</string>
				</dict>
			</dict>
			<key>match</key>
			<string>width\(([0-9]+)\)</string>
			<key>name</key>
			<string>support.function.mackerel</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.mackerel</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.mackerel</string>
				</dict>
			</dict>
			<key>match</key>
			<string>addr\(([A-z0-9_]+), ([A-z0-9_]+)\)</string>
			<key>name</key>
			<string>support.function.mackerel</string>
		</dict>
		<dict>
			<key>match</key>
			<string> ro | rw | wo</string>
			<key>name</key>
			<string>entity.name.tag</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>mackerel</string>
	<key>uuid</key>
	<string>f19xx972-704a-4d50-8e63-6dc4a707da40</string>
</dict>
</plist>
