<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>pleco</string>
	</array>
	<key>name</key>
	<string>Pleco</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>subsystem|event</string>
			<key>name</key>
			<string>keyword.control.pleco</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.pleco</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.pleco</string>
		</dict>
		<dict>
			<key>match</key>
			<string>//.*</string>
			<key>name</key>
			<string>comment.line.pleco</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>pleco</string>
	<key>uuid</key>
	<string>caba87e5-9c79-4d69-a319-73998d601efe</string>
</dict>
</plist>
